### ISSUE TITLE
dockutil --add fails with several errors 

### ISSUE THREAD

**Issue by tjluoma** [kcrawford/dockutil#84] opened 2019-08-06 00:56 UTC
I've tried several commands like these:

```
dockutil --add '/Applications'
dockutil --add /Applications/Launchpad.app
dockutil --add '/Volumes' --view list --display stack --sort name
```

and they all failed with similar (but entirely-cryptic-to-me) errors, which I collected here 

[dockutil-errors.txt](https://github.com/kcrawford/dockutil/files/3469873/dockutil-errors.txt)

This is on a MacBookAir8,1 aka MacBook Air (Retina, 13-inch, 2018) which is running:

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
```

(aka "latest Mojave, non-beta)

Oh and I'm using dockutil version `2.0.5` installed via Homebrew.

**Comment by kcrawford** [comment] 2019-08-06 05:50
It looks like you are manually removing sections from the dock plist that dockutil expects.

dockutil should handle that situation so it needs to be fixed but in the meantime maybe if you restart the dock it will add the sections back. Otherwise drag items in and out of your dock to get the sections back.

When python expects something but it is missing you often get an attribute error.

Kyle

**Comment by tjluoma** [comment] 2019-08-06 16:32
Ah, yes, that’s true… this was part of several modifications that I was trying to make at once. One issue that I was trying to avoid was restarting the dock after each modification. Perhaps I should do it once after `defaults write` and `defaults delete` commands and before the `dockutil` commands. 

Is there a way in `dockutil` to add several folders/apps to the dock and then restart the dock once, rather than after each `dockutil` command?

Thanks!

Tj

**Comment by kcrawford** [comment] 2019-08-06 19:10
Yes I think there is a no restart option you can use.

Kyle

**Comment by tjluoma** [comment] 2019-08-06 20:17
On Tue, Aug 6, 2019, at 3:10 PM, Kyle Crawford wrote:
> Yes I think there is a no restart option you can use.
> 

Ah! So there is… `--no-restart`

Does `killall Dock` suffice to manually restart the Dock, or does `dockutil` have some special method of doing it better?

Thanks again!

Tj

**Comment by kcrawford** [comment] 2019-08-06 23:48
I think killall is what dockutil is using.  Should be fine.

Kyle

**Comment by tep74** [comment] 2019-08-09 22:14
I'm seeing similar errors just when running a simple --add

**Comment by Gerst20051** [comment] 2019-12-10 00:21
Yeah, this was working perfectly fine before I updated to macOS Catalina.

When I run `dockutil --add /Applications/Slack.app` I get the following error message.

```
Slack already exists in dock. Use --replacing 'Slack' to update an existing item
item /Applications/Slack.app was not added to Dock
```

That error message comes from this line: https://github.com/kcrawford/dockutil/blob/b2900281ba51575d1cda7f6905382e89df5d286d/scripts/dockutil#L569

We can see that it's using the plist file on this line: https://github.com/kcrawford/dockutil/blob/b2900281ba51575d1cda7f6905382e89df5d286d/scripts/dockutil#L245

`~/Library/Preferences/com.apple.dock.plist`

Maybe something changed with this plist file?

It could be related to this issue about the GUID format here: https://github.com/kcrawford/dockutil/issues/83

**Comment by kcrawford** [comment] 2023-12-30 23:28
I'm going to close this older issue as dockutil was rewritten and updated.  Please open a new issue if you can still reproduce the problem in latest dockutil.  Thanks for using dockutil and reporting the issue.

**Closed by kcrawford** 2023-12-30 23:28 UTC
