### ISSUE TITLE
Placing Adobe Illustrator CC 2015.3.app or Adobe After Effects CC 2015.app Icons.

### ISSUE THREAD

**Issue by gskibum** [kcrawford/dockutil#60] opened 2016-07-25 20:18 UTC
I am having problems with dockutil placing icons for Adobe Illustrator CC 2015.3.app and Adobe After Effects CC 2015.app. The result is a question mark in the dock.

I tested with both versions 2.02 and 2.05. Macs are running El Capitan and Yosemite.

I thought it may be the odd paths that Adobe is using, but other Creative Cloud apps with similar paths do work.

Here are examples of apps & commands that dockutil does successfully work with:
dockutil --add '/Applications/Adobe Photoshop CC 2015.5/Adobe Photoshop CC 2015.5.app'
dockutil --add '/Applications/Adobe Premiere Pro CC 2015.3/Adobe Premiere Pro CC 2015.app'
dockutil --add '/Applications/Adobe Audition CC 2015.2/Adobe Audition CC 2015.app'

However, these two will not work:
dockutil --add '/Applications/Adobe After Effects CC 2015.3/Adobe After Effects CC 2015.app'
dockutil --add '/Applications/Adobe Illustrator CC 2015.3/Adobe Illustrator CC 2015.3.app'

Verbose mode feedback:
snoopy:~ conferenceroom$ /Library/Application\ Support/JAMF/bin/dockutil --add '/Applications/Adobe Illustrator CC 2015.3/Adobe Illustrator CC 2015.3.app'
snoopy:~ conferenceroom$ /Library/Application\ Support/JAMF/bin/dockutil --add '/Applications/Adobe Illustrator CC 2015.3/Adobe Illustrator CC 2015.3.app' -v
verbose: ('processing', '/Users/conferenceroom/Library/Preferences/com.apple.dock.plist')
verbose: ('adding', '/Applications/Adobe Illustrator CC 2015.3/Adobe Illustrator CC 2015.3.app')
verbose: ('adding', {'tile-data': {'file-label': u'Adobe Illustrator CC 2015.3', 'file-data': {'_CFURLStringType': 0, '_CFURLString': u'/Applications/Adobe Illustrator CC 2015.3/Adobe Illustrator CC 2015.3.app'}, 'file-type': 32}, 'tile-type': 'file-tile', 'GUID': '227F2437-3CAB-48FE-83FD-0DC69006C652'})
verbose: ('item added at end',)

**Comment by clburlison** [comment] 2016-09-14 14:13
The issue isn't with `dockutil`. This issue is with Adobe and how they name their Applications and folders.

For example Illustrator is actually

```bash
dockutil --add "/Applications/Adobe Illustrator CC 2015.3/Adobe Illustrator.app" --no-restart
```

I'd assume After Effects is the same (I don't have a machine with it installed to verify). Welcome to the world of Adobe very inconsistent, even between apps in the same product line.

**Comment by gskibum** [comment] 2016-09-15 00:11
That is so strange. What you say works! Thank you.

The app isn't named "Adobe Illustrator.app" it's named "Adobe Illustrator CC 2015.3.app" But your modification of the command does set the icon.

It's odd that using "Adobe Photoshop CC 2015.5.app" properly places Photoshop, but "Adobe Illustrator CC 2015.3.app" does not. While "Adobe Illustrator.app" does work.

![adobe illustrator cc path](https://cloud.githubusercontent.com/assets/13141708/18534259/661664fc-7aa6-11e6-9b67-62a6ecf9c4a7.png)

![photoshop cc](https://cloud.githubusercontent.com/assets/13141708/18534281/a6f68f24-7aa6-11e6-9126-82695c5aa8e1.png)

**Comment by erikng** [comment] 2016-09-15 01:15
Adobe isn't known for consistency. I honestly think standardization is shunned upon at that company.

Sent from my iPhone

On Sep 14, 2016, at 5:11 PM, gskibum <notifications@github.com<mailto:notifications@github.com>> wrote:


That is so strange. What you say works! Thank you.

The app isn't named "Adobe Illustrator.app" it's named "Adobe Illustrator CC 2015.3.app" But your modification of the command does set the icon.

It's odd that using "Adobe Photoshop CC 2015.5.app" properly places Photoshop, but "Adobe Illustrator CC 2015.3.app" does not. While "Adobe Illustrator.app" does work.

[adobe illustrator cc path]<https://cloud.githubusercontent.com/assets/13141708/18534259/661664fc-7aa6-11e6-9b67-62a6ecf9c4a7.png>

[photoshop cc]<https://cloud.githubusercontent.com/assets/13141708/18534281/a6f68f24-7aa6-11e6-9126-82695c5aa8e1.png>

-

**Comment by kcrawford** [comment] 2023-12-30 20:40
I should have closed this in 2016.  Thanks for helping @clburlison

**Closed by kcrawford** 2023-12-30 20:40 UTC
